version: "3.7"

services:
  racer_dataplant:
    image: racer-kdb
    command: bash entrypoint.sh
    hostname: kdbplant
    ports:
      - 5678:5678
    working_dir: /
    environment:
      QDIR: /qScripts/
    volumes:
      - ./lgdir/:/lgdir
      - ./kdbLogs/:/kdbLogs
      - ./logOuts/:/logOuts