version: "3.7"

services:
  racer_dataplant:
    image: racer-kdb
    command: bash /racer_dataplant/daemon.sh
    hostname: kdbplant
    ports:
      - 5001:5001
      - 5002:5002
      - 5003:5003
      - 5004:5004
      - 5005:5005
    working_dir: /
    environment:
      QDIR: /racer_dataplant/qScripts/
    volumes:
      - ./lgdir/:/racer_dataplant/lgdir
      - ./kdbLogs/:/racer_dataplant/kdbLogs
      - ./logOuts/:/racer_dataplant/logOuts