version: "3.7"

services:
  racer_dataplant:
    image: racer-kdb
    command: bash /racer_dataplant/daemon.sh
    hostname: kdbplant
    ports:
      - 5500:5500
      - 5501:5501
      - 5502:5502
      - 5503:5503
      - 5504:5504
      - 5505:5505
    working_dir: /
    environment:
      QDIR: /racer_dataplant/qScripts/
      INTERFACES_DIR: /racer_dataplant/kdbLogs/
      CONFIG_DIR: /racer_dataplant/config/
      QROS_DIR: /racer_dataplant/qROS/
      LOGFILES_DIR: /racer_dataplant/kdbLogs/
      KDBLOG_DIR: /racer_dataplant/kdbLogs/
    volumes:
      - ./lgdir/:/racer_dataplant/lgdir
      - ./kdbLogs/:/racer_dataplant/kdbLogs
      - ./logOuts/:/racer_dataplant/logOuts
      - ${ROS2KDB_DIR}/configs:/racer_dataplant/config
      - ${ROS2KDB_DIR}/q:/racer_dataplant/qROS